---


exp:  stainer_basic_cmp/exp1
seed: 42

loader:
  norm_method: global_minmax
  train_batch: 8
  val_batch:   1
  num_workers: 10
  pin_memory:  true

G:
  name: stainer_basic
  params:
    full_size:       1024
    input_channels:  3
    output_channels: 3
    init_channels:   32
    levels:          4
    encoder1_blocks: 3
    style_type:      mod
    style_linear:    true
    style_blocks:    9
    norm_type:       batch
    dropout:         0.2
    output_lowres:   true
  init:
    init_type: normal
    init_gain: 0.02

D:
  name: patch_gan
  params:
    input_channels: 3
    init_channels:  32
    num_layers:     4
    norm_type:      batch
  init:
    init_type: normal
    init_gain: 0.02

C:
  name: comparator_basic
  params:
    full_size:      1024
    input_channels: 3
    init_channels:  32
    max_channels:   256
    levels:         4
    norm_type:      batch
    dropout:        0.2
  init:
    init_type: normal
    init_gain: 0.02

loss:
  cls:
    mode:   focal
    weight: 5.0
  rec:
    mode:   mae
    weight: 10.0
  sim:
    mode:   ssim
    weight: 1.0
  gan:
    mode:   lsgan
    weight: 1.0
  cmp:
    mode:   csim
    weight: 1.0

optimizer:
  name: AdamW
  params:
    lr:           0.001
    betas:        [0.5, 0.9]
    weight_decay: 0.05

scheduler:
  min_lr: 0.0
  warmup: 50

trainer:
  epochs:     150
  accum_iter: 1
  diffaug:    false
  ema:        true
  low_weight: 1.0
  apply_cmp:  true
  start_cmp:  50
  ckpt_freq:  1000
  print_freq: 100


...
